[build]
  command = "yarn run build"
  functions = "netlify/functions"
  publish = "dist"

  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  [dev]
    command = "yarn start"
    port = 5173
    publish = "dist"

